username= input('whats your name?')
password= input('enter your password')
secret= '*' * len(password)
lengthofpassowrd= len(password)
print(f'{username}, your password {secret} is {lengthofpassowrd} letters long.')